### ISSUE TITLE
BE. Replace local storage with json file on server

### ISSUE THREAD

**Issue by yuristsepaniuk** [peterbabukh/learnwords3#1]
Current WordsCollection contains this code
```javascript
localStorage: new Backbone.LocalStorage("words")
```
*  create separate branch, later you will merge it into master, name branch 'be_first_step'
*  create json/words.json file in the root
*  move all data to json file, I want json file to look like this:
```json
[{
  "wordGroup": "задания",
  "enWord": "listen",
  "ruWord": "слушать",
  "enSynonyms": "listen",
  "ruSynonyms": "слушать",
  "grade": 4,
  "lesson": 0.1
}, {

}
]
```
It will be easier to move to server side later, because we gonna update this server file up there using nodejs. But for now lets place it on FrontEnd side under json/words.json.
*  change WordsCollection as follows:
    *  remove this
        ```javascript
          localStorage: new Backbone.LocalStorage("words")
        ```
    *  add this
        ```javascript
          url: 'js/json/words.json'
        ```
    * fix all issues, like collection.on and etc, because we just removed localStorage support from collection
* study node js server, you should know how to handle request/response using node js. There are a few http methods: GET, POST, PUT, DELET and etc. Start from GET. I want you to place json/words file on server side and set up appropriate http headers create GET request, and get GET response from Node Server. Mask this request as the following url: /learnwords/v1/words
* change WordsCollection as follows
```javascript
  url: '/learnwords/v1/words'
```
* start Node server and navigate your browser to http://localhost:8001/index.html Depends on how you start you server, where is your root.
* make sure that your application loads data correctly.
* PUT request, rename WordItem to WordModel, replace localStorage with url: '/learnwords/v1/word'
* Call model.save on client side.
* Task is to handle PUT request and stop there. So you get data on server side? Good.
* Learn how to work with file systems on Node JS. Server side contains file system, in your case it is the same file system where you run your code, in general case it might be file system on hosting server. You must know how read json files, how create json files with data and remove json files. It is not possible to change just part of json file without special streams, so please update everything within file when handling PUT request.
*  so if words array doesn't contain it, just add this word to the end of array, if there is word with such id --> replace this object in memory array and emit it all to empty json file on server side.
* think about how you can leverage server side, for example it will be great to handle answer to the question through server, because somebody might load other data to the server during the test.

Basic idea is to study file system using node js, and to handle GET, POST and PUT requests/responses. FYI GET -> to get collection data, or get answer to the question by id. PUT -> to update word with given id. POST -> to create word without id, don't forget to generate it before storing to json file. Later you might store reports on server side, so that teacher can verify reports.

**Comment by peterbabukh** [comment]
I'm on my way of learning node.js. As soon as I can move further on, I will do it according to your instructions.

**Comment by peterbabukh** [comment]
- I pushed the draft basic structure of the server side. It is pretty raw, with commented links and code i'm going to use later on.

- in the draft structure you will not see folder 'data' or any similar folder which you might choose for the batabase storage. BTW I chose mongoDB document-based database.

- currently this code allows you to see draft structure and test draft schemas. localhost:3000/save or localhost:3000/save/:name will save user into db and show the data saved, link /main shows all users saved, /fieldset shows words.json contents, and /clear clears all the db contents. it is all done for testing purposes.

-now i am going to refactor /public folder so that to provide requests and support backend. In other words I will replace test functionalities for the needed ones.

- after that I will procede to proper error handling, validation, logins, etc

**Comment by peterbabukh** [comment]
Please, close this sprint and pass this issue to the next sprint, as now i am currently working on refactoring of the code to create server side based on nodejs + mongodb + mongoose. I have already implemented save of words to the server and their get upon fetch and modification as well. Working on further refactoring now.

**Comment by peterbabukh** [comment]
By now I have done implementation of new user creation and save on the back end, logging in and signing up for the app, server start and mongodb data save. Currently i am putting together the ready front end and back end.
