### ISSUE TITLE
Node JS first steps

### ISSUE THREAD

**Issue by peterbabukh** [peterbabukh/learnwords3#4]
The current target is to learn Node.js, so that to refactor learnwords3.

**Comment by peterbabukh** [comment]
Started learning documentation on https://nodejs.org/api/all.html

**Comment by yuristsepaniuk** [comment]
Peter, https://nodejs.org/api/all.html is a bad start, please take a look at https://www.youtube.com/watch?v=czmulJ9NBP0 I've just watched 2 hours, looks promising.

**Comment by yuristsepaniuk** [comment]
Also please assign to me in case of questions, so that I can answer. If it assigned to you, that means that ball on your side and you have to do smth. Same for me, don't hesitate to assign to me a lot of questions.

**Comment by yuristsepaniuk** [comment]
Please don't watch youtube video I posted in prev comment (https://www.youtube.com/watch?v=czmulJ9NBP0) Presenters are bad, talking about other stuff, 25% of node is there! Sorry, I just finished it, do not recommend!

**Comment by yuristsepaniuk** [comment]
check this out https://www.youtube.com/watch?v=YozRK2kv4r0
3 hours of good examples

**Comment by peterbabukh** [comment]
thank you. currently I'm reading http://jsman.ru/express/ , http://learn.javascript.ru/nodejs-screencast , and loads of project codes on github. I'll check out your link as well too.
